App\Entity\City:
  properties:
    latitude:
      - Range:
          min: -90
          max: 90
          groups: [edit]
      - NotBlank:
          groups: [edit]
    longitude:
      - Range:
          min: -180
          max: 180
          groups: [edit]
      - NotBlank:
          groups: [edit]
