#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
weather_in_city:
  path: /weather/{city}
  controller: App\Controller\WeatherController::cityAction
  requirements:
      city: '\d+'

weather_in_city_by_country:
  path: /weather/{country}/{city}
  controller: App\Controller\WeatherController::cityByNameAction
  requirements:
app_logout:
  path: /logout
  methods: GET